---
- name: Pull OWASP Juice Shop Docker image
  containers.podman.podman_image:
    name: docker.io/bkimminich/juice-shop:latest
    state: present

- name: Ensure port 3000/tcp is open
  ansible.posix.firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Run OWASP Juice Shop container
  containers.podman.podman_container:
    name: juice-shop
    image: docker.io/bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
    state: started
    restart_policy: always
